'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace CoorMedia
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="CoorMedia.CoordinacionSoap")>  _
    Public Interface CoordinacionSoap
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento asignatura del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/media", ReplyAction:="*")>  _
        Function media(ByVal request As CoorMedia.mediaRequest) As CoorMedia.mediaResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/media", ReplyAction:="*")>  _
        Function mediaAsync(ByVal request As CoorMedia.mediaRequest) As System.Threading.Tasks.Task(Of CoorMedia.mediaResponse)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class mediaRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="media", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As CoorMedia.mediaRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As CoorMedia.mediaRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class mediaRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public asignatura As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal asignatura As String)
            MyBase.New
            Me.asignatura = asignatura
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class mediaResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="mediaResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As CoorMedia.mediaResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As CoorMedia.mediaResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class mediaResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public mediaResult As Double
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal mediaResult As Double)
            MyBase.New
            Me.mediaResult = mediaResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface CoordinacionSoapChannel
        Inherits CoorMedia.CoordinacionSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class CoordinacionSoapClient
        Inherits System.ServiceModel.ClientBase(Of CoorMedia.CoordinacionSoap)
        Implements CoorMedia.CoordinacionSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function CoorMedia_CoordinacionSoap_media(ByVal request As CoorMedia.mediaRequest) As CoorMedia.mediaResponse Implements CoorMedia.CoordinacionSoap.media
            Return MyBase.Channel.media(request)
        End Function
        
        Public Function media(ByVal asignatura As String) As Double
            Dim inValue As CoorMedia.mediaRequest = New CoorMedia.mediaRequest()
            inValue.Body = New CoorMedia.mediaRequestBody()
            inValue.Body.asignatura = asignatura
            Dim retVal As CoorMedia.mediaResponse = CType(Me,CoorMedia.CoordinacionSoap).media(inValue)
            Return retVal.Body.mediaResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function CoorMedia_CoordinacionSoap_mediaAsync(ByVal request As CoorMedia.mediaRequest) As System.Threading.Tasks.Task(Of CoorMedia.mediaResponse) Implements CoorMedia.CoordinacionSoap.mediaAsync
            Return MyBase.Channel.mediaAsync(request)
        End Function
        
        Public Function mediaAsync(ByVal asignatura As String) As System.Threading.Tasks.Task(Of CoorMedia.mediaResponse)
            Dim inValue As CoorMedia.mediaRequest = New CoorMedia.mediaRequest()
            inValue.Body = New CoorMedia.mediaRequestBody()
            inValue.Body.asignatura = asignatura
            Return CType(Me,CoorMedia.CoordinacionSoap).mediaAsync(inValue)
        End Function
    End Class
End Namespace
