'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Comprobar
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://sw14.hol.es/ServiciosWeb/comprobarmatricula.php?wsdl", ConfigurationName:="Comprobar.MatriculasPortType")>  _
    Public Interface MatriculasPortType
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://sw14.hol.es/ServiciosWeb/comprobarmatricula.php/comprobar", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults:=true, Use:=System.ServiceModel.OperationFormatUse.Encoded)>  _
        Function comprobar(ByVal x As String) As <System.ServiceModel.MessageParameterAttribute(Name:="z")> String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://sw14.hol.es/ServiciosWeb/comprobarmatricula.php/comprobar", ReplyAction:="*")>  _
        Function comprobarAsync(ByVal x As String) As <System.ServiceModel.MessageParameterAttribute(Name:="z")> System.Threading.Tasks.Task(Of String)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface MatriculasPortTypeChannel
        Inherits Comprobar.MatriculasPortType, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class MatriculasPortTypeClient
        Inherits System.ServiceModel.ClientBase(Of Comprobar.MatriculasPortType)
        Implements Comprobar.MatriculasPortType
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function comprobar(ByVal x As String) As String Implements Comprobar.MatriculasPortType.comprobar
            Return MyBase.Channel.comprobar(x)
        End Function
        
        Public Function comprobarAsync(ByVal x As String) As System.Threading.Tasks.Task(Of String) Implements Comprobar.MatriculasPortType.comprobarAsync
            Return MyBase.Channel.comprobarAsync(x)
        End Function
    End Class
End Namespace
